### ISSUE TITLE
Which branch would you recommend?

### ISSUE THREAD

**Issue by cspencerjones** [lysun0725/drifters#2]
Hi @lysun0725  and @MJHarrison-GFDL , 
I have been trying to get this code working, and I'm making progress, but one problem I have is that there are lots of branches and it's not clear which one to use. luyu-testing is most up to date, but it does not have particle_driver.F90. The most up-to-date branch that has that is adcroft_testing. Would you recommend starting there?
Thanks in advance for any pointers!

**Comment by lysun0725** [comment]
Hi @cspencerjones,
The branch luyu-testing is the latest code. It is built up for the on-line drifter simulation for MOM6, therefore it doesn't need the particle_driver.F90, which was designed only for the off-line drifter simulation. @MJHarrison-GFDL is helping me on pulling request toward GFDL repository for adding the corresponding particle interfaces to MOM.F90 and I think it will complete soon. We will let you know once it is done.
Thanks.

**Comment by cspencerjones** [comment]
Thanks for getting back to me. It would be really helpful to me if this was added soon! Please can you keep me updated on progress (or if you stop working on it for some reason, in which case I will look at alternatives)?

**Comment by MJHarrison-GFDL** [comment]
@cspencerjones Luyu has written and tested the particle code on her luyu-testing branch, so it would be best if you buiilt on that code.  This week, we will make a PR to dev/gfdl which will contain the interfaces to the on-line drifters. The actual drifter code will reside in an external repository (e.g. data assimilation, BGC are also external repositories). If you have any modifications in mind to the MOM interfaces contained on Luyu's branch, then this would be good time to discuss. You should be able to develop your forked repository independently, as long as the interfaces are compatible.

**Comment by cspencerjones** [comment]
> If you have any modifications in mind to the MOM interfaces contained on Luyu's branch, then this would be good time to discuss.

Are you talking about [this code](https://github.com/lysun0725/MOM6/blob/316bd988f4538b9a1a37977d970620fc294e5e7c/src/core/MOM.F90#L1432-L1435)? It seems good to me, but I haven't dug into all the details. My hope is to advect the particles in 3D, and one thing I am concerned about is what will happen during a vertical regridding step, but I think that is probably separate code that I will have to write myself.

**Comment by MJHarrison-GFDL** [comment]
OK. Thanks for the feedback. You are correct that additional code needs to be written to handle 3-d advection. Feel free to reach out if you need some advice on  the code.

**Comment by cspencerjones** [comment]
I've been attempting to run the code based on what you have at the moment (https://github.com/lysun0725/drifters/tree/luyu-testing plus https://github.com/lysun0725/MOM6/tree/drifter_interfaces). The main issue I am running into seems to be that the expected input file (drifters.res.nc) is not exactly the same as the one from the example that is created by this file: https://github.com/lysun0725/MOM6-drifter-example/blob/luyu-part-testing/ocean_only/double_gyre/initialize_drifters.py. Do you have an updated version somewhere? Thanks - I know you are working on this so I'm not expecting it to run perfectly!

**Comment by MJHarrison-GFDL** [comment]
Hi @cspencerjones . I have not run the drifter examples recently but I can see where several fields were added using  [register_restart_field](https://github.com/lysun0725/drifters/blob/luyu-testing/MOM_particles_io.F90#L214) . Should be straighforward enough to modify said python code or write directly into a cdl file for testing.

**Comment by lysun0725** [comment]
Hi @cspencerjones,
You can check the code at https://github.com/lysun0725/GoM/blob/master/drifter_restart.py to generate the initialized drifter positions. Just replace "levs=[15,15,15]" with "levs=[1,1,1]", since the current drifter module simulates the drifters at 1m depth by default.

**Comment by cspencerjones** [comment]
It works! I have particle trajectories. Thanks for your help with this: I will remain in touch  so that I can give you proper credit and/or coauthorship depending on where this goes. (and @MJHarrison-GFDL I will probably take you up on that offer to talk about how to code the 3D trajectories).
